# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Deep Paper Pool
tagline:             'really deep.'
description:         'Keep reading.'
url:                 https://ht93.github.io/
baseurl:             /
plugins:             [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"
markdown:            kramdown


# About/contact
author:
  name:              ht93
  url:               https://ht93.github.io
  email:             hetong1115@gmail.com

# Custom vars
version:             1.0.0

